-- INSERT Tbl_Alunos
INSERT INTO TBL_ALUNOS(NOME) VALUES ('Carlos');
INSERT INTO TBL_ALUNOS(NOME) VALUES ('Luciene');
INSERT INTO TBL_ALUNOS(NOME) VALUES ('Matheus');
INSERT INTO TBL_ALUNOS(NOME) VALUES ('Vinicius');
